#!/usr/bin/env python3
from sys import argv
from error_handling import error_handling
from file import load_data_from_file
from calc import deriv, sec_deriv, sec_estimated


def display_help():
    print("USAGE")
    print("\t./109titration file\n")
    print("DESCRIPTION")
    print("\tfile\ta csv containing \"vol;ph\" lines")


if __name__ == "__main__":
    if len(argv) == 2 and argv[1] == "-h":
        display_help()
        exit(0)
    if error_handling(argv):
        exit(84)
    keys, values = load_data_from_file(argv[1])
    keys, values = deriv(keys, values)
    keys, values = sec_deriv(keys, values)
    sec_estimated(keys, values)
